In [1]:
import numpy as np

In [13]:
#criando um array em python
py_arr = [1,2,3,4]
type(py_arr)

list

In [12]:
#criando um array em numpy
np_arr = np.array([1,2,3,4])
type(np_arr)

numpy.ndarray

In [7]:
#conteúdo do python array
py_arr

[1, 2, 3, 4]

In [8]:
#conteúdo do np array
np_arr

array([1, 2, 3, 4])

In [16]:
#convertendo python array em np array
new_np_arr = np.array(py_arr)
print(type(new_np_arr))
new_np_arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [25]:
#convertendo np array in python array
new_py_arr = new_np_arr.tolist
print(type(new_py_arr))
new_np_arr

<class 'builtin_function_or_method'>


array([1, 2, 3, 4])

In [29]:
#slicing intervalo fechado de 0 até 2 (3 não é incluso)
np_arr[0:3]

array([1, 2, 3])

In [37]:
#slicing pegando último elemento
np_arr[-1:]

array([4])

In [38]:
#imprimindo a lista de forma inversa
np_arr[::-1]

array([4, 3, 2, 1])